# -*- coding: utf-8 -*-
"""Assignment 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dL-DmKnSwrCvKg2H-z_9ntM0OehumXBj
"""

day = [1,2,3,4,5,6,7]
sales1 = [160,150,140,145,175,165,180]
sales2 = [70,90,160,150,140,145,175]
plt.title("Sales per day", color="c")
plt.xlabel("Days", color="b")
plt.ylabel("Sales", color="b")
plt.plot(day, sales1, "ro-", linewidth=1, markersize=2)
plt.plot(day, sales2, "g*-", linewidth=2, markersize=4)