# -*- coding: utf-8 -*-
"""Assignment 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vm84gFAdqdTh8PEoDLwYjxLiaB2iEnyN
"""

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
# %matplotlib inline
import seaborn as sns
from numpy.random import randn
df=pd.DataFrame(randn(10,4),columns=['a','b','c','d'])
df.plot.bar()
plt.title("Bar Graph")