# -*- coding: utf-8 -*-
"""Assignment 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mN4YmkZ1tdIb6EuHDkZeKHp7TfHISF5V
"""

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
# %matplotlib inline
import seaborn as sns
from numpy.random import randn

fmri = sns.load_dataset("fmri")
sns.relplot(x = "timepoint", y = "signal", data = fmri, hue = "region", style = "event", size = "subject")

